### ISSUE TITLE
Replace "todo delete" with "todo cancel"

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#209]
* [ ] Implement `todo cancel` to switch status to `CANCELLES`.
* [ ] Hide cancelled events by default (we already do this, I think).
* [ ] When listing `--all`, strikethrough cancelled events (or mark them in some way).
* [ ] Recommend cancellation to deletion in the docs (the former is undoable).
