### ISSUE TITLE
meta: Recurring events

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/todoman#485]
Meta issue to track all other issues regarding recurring events:

- [ ] https://github.com/pimutils/todoman/issues/305
- [ ] https://github.com/pimutils/todoman/issues/410
- [ ] https://github.com/pimutils/todoman/issues/305
- [ ] https://github.com/pimutils/todoman/issues/304
- [ ] https://github.com/pimutils/todoman/issues/288
- [ ] https://github.com/pimutils/todoman/issues/249
